name: pta
description: Premier Trading App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  drift: ^2.6.0
  floating_bottom_bar: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5
  fpdart: ^0.4.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.5.1
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  loader_overlay: ^2.3.0
  path_provider: ^2.0.14
  responsive_builder: ^0.4.3
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  webview_flutter: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  drift_dev: ^2.6.0
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
